### PR TITLE
Fix for when 'pairs' is not returned

### PR DESCRIPTION
**Pull request by neochine**
Functions returning pairs need not to be changed given it returns [] which is expected. Functions returning pair needs to decide whether to return None or raising Error

### CODE REVIEW

**Comment by neochine** [comment]
Needs to modify list as well but pretty sure other function just returned [] 
```
screener.get_token_pairs('...')
    return [TokenPair(**pair) for pair in resp["pairs"]]
TypeError: 'NoneType' object is not iterable
```

**Comment by nixonjoshua98** [comment]
Looks fine. Maybe update the method signature to return Optional?

**Comment by neochine** [comment]
Does list[TokenPair] needs to be changed to list[Optional[TokenPair]]? I am not that good into typing. Modified -> TokenPair to Optional[TokenPair]

**Comment by nixonjoshua98** [comment]
The list is fine.

**Comment by nixonjoshua98** [comment]
I'll publish your fix tomorrow when I have time. Thanks for fixing it

**Pull request merged**
