### PR TITLE
Add support for new Dexscreener API

### LINKED ISSUE #10: Dexcreener API update
Looking at [Dexscreener API reference](https://docs.dexscreener.com/api/reference), it looks like they made some changes that are not yet reflected in this SDK.

Namely, here are the changes:

1. New methods:
- Get the latest token profiles
- Get the latest boosted tokens
- Get the tokens with most active boosts
- Check orders paid for of token
2. Base URL changed (https://api.dexscreener.io -> https://api.dexscreener.com) (Note: https://api.dexscreener.io still works, but it redirects to .com)
3. Rate limits on existing methods changed from 100 requests per minute to 300

Since I needed one of the methods for my project, I decided to create a fork and implement it myself. I created a new class, which contains all the new methods, and also made some necessary changes to existing code. You can look at the code [here](https://github.com/Jarki/dexscreener). If you think this implementation works for the project, I’d be happy to open a pull request!

### PR DESCRIPTION
**Pull request by Jarki**
Related to issue #10

### CODE REVIEW

**Comment by nixonjoshua98** [comment]
Can we merge the two clients together?

**Comment by Jarki** [comment]
The old client makes requests to the .io address, and from what I can tell they are simply redirected to the .com one. This means that they are accessing the same endpoints, and return the same data. 

So I'd say we can. Do I name the merged client DexscreenerClient?

**Comment by Jarki** [comment]
Merged them. Now, we only have DexscreenerClient with all the methods.

**Comment by nixonjoshua98** [comment]
Sorry for the delay, I have released your change as v1.2

**Pull request merged**
